# backend/app/models/evidence.py
"""
Evidence model — the per-match Evidence Inventory.

Covers:
  US6:  Evidence is role-specific (Defense only sees defense evidence, etc.)
  US8:  Visual Evidence Folder — each card is a row here.
  US9:  A player attaches an evidence card to an argument (Round.attached_evidence_id).
  US10: Used evidence cards are flagged with is_used=True so they are
        marked/removed from the folder after being played.
"""

import enum
import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, Integer, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class EvidenceRole(str, enum.Enum):
    """US6 — which role this evidence card belongs to."""
    DEFENSE = "defense"
    PROSECUTION = "prosecution"
    SHARED = "shared"   # visible to both sides (e.g., case facts)


class Evidence(Base):
    __tablename__ = "evidence"

    # ── Primary key ──────────────────────────────────────────────────────────
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True,
    )

    # ── Parent match ──────────────────────────────────────────────────────────
    match_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("matches.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Card content (generated by the AI Clerk) ──────────────────────────────
    title: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)

    # ── Role assignment (US6) ─────────────────────────────────────────────────
    assigned_role: Mapped[EvidenceRole] = mapped_column(
        Enum(EvidenceRole, name="evidence_role_enum"),
        nullable=False,
    )

    # ── Display order inside the Evidence Folder (US8) ───────────────────────
    card_order: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # ── Usage tracking (US10) ─────────────────────────────────────────────────
    is_used: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    used_in_round: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # ── Timestamps ───────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    match: Mapped["Match"] = relationship("Match", back_populates="evidence_items")

    def __repr__(self) -> str:
        return (
            f"<Evidence id={self.id} title={self.title!r} "
            f"role={self.assigned_role} used={self.is_used}>"
        )
